### ISSUE TITLE
Implementation of Time Tracking:

### ISSUE THREAD

**Issue by vidm27** [vidm27/tictacwork#1]
![image](https://github.com/vidm27/tictacwork/assets/47898368/5adc525a-e7a0-4ead-9dcc-f8c2dd186dda)

- [x] Make component card time task
- [x] Make feature to start/stop tracking time
- [x] Make clean tracking time
- [x] Add task to list task time
